from pathlib import Path

Path('scripts/test-dashboard-fc-unit.mjs').write_text('''import test from "node:test";\nimport assert from "node:assert/strict";\nimport fs from "node:fs";\n\nconst dashboard=fs.readFileSync("dashboard.html","utf8");\nconst widget=fs.readFileSync("fc-chart.js","utf8");\n\ntest("dashboard uses the unified sequential-HM FC widget",()=>{\n  assert.doesNotMatch(dashboard,/id="fcSection"/);\n  assert.doesNotMatch(dashboard,/renderFuelConsumption\\(mtdRows\\)/);\n  assert.match(dashboard,/hostId:"dashboardFcChart"/);\n  assert.match(widget,/validFuel\\/totalHm/);\n  assert.match(widget,/HM JALAN VALID/);\n  assert.match(widget,/Ringkasan Unit Terpilih/);\n});\n\ntest("aggregate FC is ratio of valid fuel totals to valid HM totals",()=>{\n  const rows=[{fuel:100,hm:10},{fuel:300,hm:20}];\n  const weighted=rows.reduce((s,r)=>s+r.fuel,0)/rows.reduce((s,r)=>s+r.hm,0);\n  const average=rows.reduce((s,r)=>s+r.fuel/r.hm,0)/rows.length;\n  assert.equal(weighted,400/30);\n  assert.notEqual(weighted,average);\n  assert.match(widget,/validFuel\\/totalHm/);\n});\n''',encoding='utf-8')

Path('scripts/test-fc-chart-widget.mjs').write_text('''import fs from "node:fs";\nconst widget=fs.readFileSync("fc-chart.js","utf8");\nconst dash=fs.readFileSync("dashboard.html","utf8");\nconst log=fs.readFileSync("logsheet.html","utf8");\nfor(const needle of ["fetchBaselines","hm>=previous","validFuel/totalHm","Maksimal 10 unit","HM turun/reset diabaikan"]){if(!widget.includes(needle))throw new Error(`missing FC safety marker: ${needle}`);}\nif(!dash.includes('hostId:"dashboardFcChart"')||!dash.includes('autoLoad:true'))throw new Error('Dashboard FC widget is not active');\nif(!log.includes('hostId:"logsheetFcChart"')||!log.includes('collapsedByDefault:true')||!log.includes('autoLoad:false'))throw new Error('Logsheet FC widget must be lazy and collapsed by default');\nif(!log.includes('Tampilkan Grafik FC') && !widget.includes('Tampilkan Grafik FC'))throw new Error('FC hide/show control missing');\nconsole.log('FC chart widget regression checks passed');\n''',encoding='utf-8')

p=Path('scripts/test-fc-data-contract.mjs')
s=p.read_text(encoding='utf-8').replace('fc-chart\\.js\\?v=20260912c','fc-chart\\.js\\?v=20260912d')
p.write_text(s,encoding='utf-8')
