from pathlib import Path

p = Path('daily-report.html')
s = p.read_text(encoding='utf-8')

css_anchor = '''.stock-total-side .stock-total-note{color:var(--kpp-muted)!important;font-size:11px}\n\n/* Stock individual tidak lagi penuh warna */'''
css_new = '''.stock-total-side .stock-total-note{color:var(--kpp-muted)!important;font-size:11px}\n.stock-total-main{min-width:245px}\n.stock-total-main .stock-total-caption{margin-top:9px;color:var(--kpp-muted);font-size:10px;font-weight:700}\n.stock-total-side{flex:1;min-width:360px;max-width:none;display:flex;flex-direction:column;gap:10px}\n.stock-total-progress-head{display:flex;align-items:center;justify-content:space-between;gap:12px;font-size:10px;color:var(--kpp-muted);font-weight:800}\n.stock-total-progress-head strong{font-size:12px;color:var(--kpp-text)}\n.stock-total-progress{height:11px;border-radius:999px;background:#eef2f7;overflow:hidden;box-shadow:inset 0 1px 2px rgba(15,23,42,.08)}\n.stock-total-progress-fill{display:block;height:100%;border-radius:inherit;background:var(--kpp-green);transition:width .25s ease}\n.stock-total-progress-fill.low{background:var(--kpp-yellow)}\n.stock-total-progress-fill.critical{background:var(--kpp-red)}\n.stock-total-progress-fill.high{background:var(--kpp-orange)}\n.stock-total-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}\n.stock-total-kpi{padding:8px 10px;border:1px solid #e8edf3;border-radius:9px;background:#f8fafc;min-width:0}\n.stock-total-kpi small{display:block;color:var(--kpp-muted);font-size:8px;font-weight:900;letter-spacing:.035em;margin-bottom:3px}\n.stock-total-kpi strong{display:block;color:var(--kpp-text);font-size:12px;line-height:1.25;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}\n.stock-total-kpi.status-safe strong{color:#166534}.stock-total-kpi.status-low strong{color:#b45309}.stock-total-kpi.status-critical strong{color:#b91c1c}.stock-total-kpi.status-high strong{color:#c2410c}\n.stock-total-status-row{display:flex;flex-wrap:wrap;gap:6px}\n.stock-total-chip{display:inline-flex;align-items:center;gap:5px;padding:4px 8px;border-radius:999px;border:1px solid #e5e7eb;background:#fff;color:#475569;font-size:9px;font-weight:900}\n.stock-total-chip.safe{color:#166534;border-color:#bbf7d0;background:#f0fdf4}.stock-total-chip.low{color:#b45309;border-color:#fde68a;background:#fffbeb}.stock-total-chip.critical{color:#b91c1c;border-color:#fecaca;background:#fef2f2}.stock-total-chip.high{color:#c2410c;border-color:#fed7aa;background:#fff7ed}\n\n/* Stock individual tidak lagi penuh warna */'''
assert css_anchor in s, 'CSS anchor not found'
s = s.replace(css_anchor, css_new, 1)

mobile_anchor = '''@media(max-width:850px){\n  .panel{padding:14px}\n  .stock-total-main strong{font-size:30px}\n}\n'''
mobile_new = '''@media(max-width:850px){\n  .panel{padding:14px}\n  .stock-total-main strong{font-size:30px}\n  .stock-total-card{align-items:stretch}\n  .stock-total-main{min-width:190px}\n  .stock-total-side{min-width:0}\n}\n@media(max-width:600px){\n  .stock-total-main{min-width:0;width:100%}\n  .stock-total-side{min-width:0;width:100%}\n  .stock-total-kpis{grid-template-columns:1fr 1fr}\n  .stock-total-kpi:last-child{grid-column:1/-1}\n  .stock-total-status-row{gap:5px}\n}\n'''
assert mobile_anchor in s, 'mobile anchor not found'
s = s.replace(mobile_anchor, mobile_new, 1)

old_decl = '''  const criticalList=[];\n  const highList=[];\n\n  STORAGES.forEach(storage=>{'''
new_decl = '''  const criticalList=[];\n  const highList=[];\n  const statusCounts={safe:0,low:0,critical:0,high:0};\n\n  STORAGES.forEach(storage=>{'''
assert old_decl in s, 'render decl anchor not found'
s = s.replace(old_decl, new_decl, 1)

old_cls = '''    const cls=capacityClass(pct);\n    const width=Math.max(0,Math.min(pct,100));'''
new_cls = '''    const cls=capacityClass(pct);\n    statusCounts[cls]=(statusCounts[cls]||0)+1;\n    const width=Math.max(0,Math.min(pct,100));'''
assert old_cls in s, 'class anchor not found'
s = s.replace(old_cls, new_cls, 1)

old_total = '''  const total=Object.values(stock).reduce((a,b)=>a+n(b),0);\n  const totalPct=TOTAL_CAPACITY>0 ? (total/TOTAL_CAPACITY)*100 : 0;\n  const totalCls=capacityClass(totalPct);\n  const totalClass=totalCls==="critical"?"danger":totalCls==="low"||totalCls==="high"?"warn":"safe";\n\n  totalHost.innerHTML=`\n    <div class="stock-total-card ${totalClass}">\n      <div class="stock-total-main">\n        <small>TOTAL STOCK ALL WHS</small>\n        <strong>${fmt(total)} L</strong>\n      </div>\n      <div class="stock-total-side">\n        <div class="capacity-wrap">\n          <div class="capacity-row">\n            <span>Total kapasitas ${fmt(TOTAL_CAPACITY)} L</span>\n            <span class="capacity-text ${totalCls}">${pctFmt(totalPct)}% terisi</span>\n          </div>\n        </div>\n        \n      </div>\n    </div>\n  `;'''
new_total = '''  const total=Object.values(stock).reduce((a,b)=>a+n(b),0);\n  const totalPct=TOTAL_CAPACITY>0 ? (total/TOTAL_CAPACITY)*100 : 0;\n  const totalWidth=Math.max(0,Math.min(totalPct,100));\n  const totalCls=capacityClass(totalPct);\n  const totalClass=totalCls==="critical"?"danger":totalCls==="low"||totalCls==="high"?"warn":"safe";\n  const totalStatusText=totalCls==="critical"?"KRITIS":totalCls==="low"?"RENDAH":totalCls==="high"?"TINGGI":"AMAN";\n  const remainingCapacity=Math.max(0,TOTAL_CAPACITY-total);\n\n  totalHost.innerHTML=`\n    <div class="stock-total-card ${totalClass}">\n      <div class="stock-total-main">\n        <small>TOTAL STOCK ALL WHS</small>\n        <strong>${fmt(total)} L</strong>\n        <div class="stock-total-caption">Gabungan ${STORAGES.length} storage aktif</div>\n      </div>\n      <div class="stock-total-side">\n        <div class="stock-total-progress-head">\n          <span>KAPASITAS TERISI</span>\n          <strong>${pctFmt(totalPct)}%</strong>\n        </div>\n        <div class="stock-total-progress" aria-label="Kapasitas stock terisi ${pctFmt(totalPct)} persen">\n          <span class="stock-total-progress-fill ${totalCls}" style="width:${totalWidth}%"></span>\n        </div>\n        <div class="stock-total-kpis">\n          <div class="stock-total-kpi">\n            <small>TOTAL KAPASITAS</small>\n            <strong>${fmt(TOTAL_CAPACITY)} L</strong>\n          </div>\n          <div class="stock-total-kpi">\n            <small>SISA KAPASITAS</small>\n            <strong>${fmt(remainingCapacity)} L</strong>\n          </div>\n          <div class="stock-total-kpi status-${totalCls}">\n            <small>STATUS GLOBAL</small>\n            <strong>${totalStatusText}</strong>\n          </div>\n        </div>\n        <div class="stock-total-status-row" aria-label="Ringkasan status storage">\n          <span class="stock-total-chip safe">AMAN ${statusCounts.safe}</span>\n          <span class="stock-total-chip low">RENDAH ${statusCounts.low}</span>\n          <span class="stock-total-chip critical">KRITIS ${statusCounts.critical}</span>\n          <span class="stock-total-chip high">TINGGI ${statusCounts.high}</span>\n        </div>\n      </div>\n    </div>\n  `;'''
assert old_total in s, 'total hero anchor not found'
s = s.replace(old_total, new_total, 1)

p.write_text(s, encoding='utf-8')

t = Path('scripts/test-daily-stock-total-hero.mjs')
t.write_text('''import test from "node:test";\nimport assert from "node:assert/strict";\nimport { readFile } from "node:fs/promises";\n\nconst daily = await readFile(new URL("../daily-report.html", import.meta.url), "utf8");\n\ntest("daily total stock hero fills empty space with progress and useful KPIs", () => {\n  assert.match(daily, /class="stock-total-progress"/);\n  assert.match(daily, /KAPASITAS TERISI/);\n  assert.match(daily, /TOTAL KAPASITAS/);\n  assert.match(daily, /SISA KAPASITAS/);\n  assert.match(daily, /STATUS GLOBAL/);\n  assert.match(daily, /statusCounts=\\{safe:0,low:0,critical:0,high:0\\}/);\n  assert.match(daily, /stock-total-chip safe/);\n  assert.match(daily, /Math\\.max\\(0,Math\\.min\\(totalPct,100\\)\\)/);\n});\n''', encoding='utf-8')
