-- KPP-FMS Stock Closing revision v1
-- Final Stock Closing is immutable for Fuelman/Atasan. Only GL/Admin may revise it.
-- Revision keeps the original closing identity/operator/session, journals before/after values,
-- and updates an existing carry-forward Opening only when that Opening still matches the old Closing.

create table if not exists private.stock_closing_revisions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  closing_id bigint not null references public.stock_closing(id) on update restrict on delete restrict,
  tanggal date not null,
  shift integer not null check (shift in (1,2)),
  storage text not null,
  changed_by uuid not null,
  changed_by_name text,
  changed_by_role text not null,
  reason text not null,
  old_data jsonb not null,
  new_data jsonb not null,
  opening_updated boolean not null default false
);

alter table private.stock_closing_revisions enable row level security;
revoke all on table private.stock_closing_revisions from public, anon, authenticated;

create index if not exists stock_closing_revisions_closing_id_idx
  on private.stock_closing_revisions(closing_id);
create index if not exists stock_closing_revisions_period_idx
  on private.stock_closing_revisions(tanggal, shift, storage, created_at desc);

create or replace function public.revise_stock_closing(
  p_rows jsonb,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text := coalesce(public.current_staff_role(), '');
  v_reason text := nullif(trim(coalesce(p_reason, '')), '');
  v_actor_name text;
  v_row record;
  v_existing public.stock_closing%rowtype;
  v_new public.stock_closing%rowtype;
  v_opening public.stock_opening%rowtype;
  v_storage text;
  v_note text;
  v_tera_version text;
  v_next_tanggal date;
  v_next_shift integer;
  v_opening_updated boolean;
  v_changed_count integer := 0;
  v_opening_count integer := 0;
begin
  if auth.uid() is null or v_role not in ('gl','admin') then
    raise exception 'Revisi Stock Akhir hanya boleh dilakukan GL atau Admin.'
      using errcode = '42501';
  end if;

  if p_rows is null
     or jsonb_typeof(p_rows) <> 'array'
     or jsonb_array_length(p_rows) = 0
     or jsonb_array_length(p_rows) > 100 then
    raise exception 'Data revisi Stock Akhir tidak lengkap.';
  end if;

  if v_reason is null or length(v_reason) < 5 then
    raise exception 'Alasan revisi wajib diisi minimal 5 karakter.';
  end if;

  select coalesce(nullif(trim(p.display_name), ''), nullif(trim(p.username), ''), auth.uid()::text)
    into v_actor_name
    from public.staff_profiles p
   where p.user_id = auth.uid()
     and p.active = true
   limit 1;
  v_actor_name := coalesce(v_actor_name, auth.uid()::text);

  for v_row in
    select *
      from jsonb_to_recordset(p_rows) as x(
        tanggal date,
        shift integer,
        storage text,
        actual_qty numeric,
        note text,
        sonding_height_cm numeric,
        tera_version text
      )
  loop
    v_storage := upper(trim(coalesce(v_row.storage, '')));
    v_note := nullif(trim(coalesce(v_row.note, '')), '');
    v_tera_version := nullif(trim(coalesce(v_row.tera_version, '')), '');

    if v_row.tanggal is null
       or v_row.shift not in (1,2)
       or v_storage = ''
       or v_row.actual_qty is null
       or v_row.actual_qty < 0
       or v_row.actual_qty = 'NaN'::numeric
       or v_row.actual_qty in ('Infinity'::numeric, '-Infinity'::numeric)
       or v_row.sonding_height_cm is null
       or v_row.sonding_height_cm < 0
       or v_row.sonding_height_cm = 'NaN'::numeric
       or v_row.sonding_height_cm in ('Infinity'::numeric, '-Infinity'::numeric)
       or v_tera_version is null then
      raise exception 'Data revisi Stock Akhir % tidak valid.', coalesce(nullif(v_storage,''), '-');
    end if;

    perform pg_advisory_xact_lock(
      hashtextextended(
        'kpp-stock-closing-revision:' || v_row.tanggal::text || ':' || v_row.shift::text || ':' || v_storage,
        0
      )
    );

    select * into v_existing
      from public.stock_closing c
     where c.tanggal = v_row.tanggal
       and c.shift = v_row.shift
       and c.storage = v_storage
     for update;

    if not found then
      raise exception 'Stock Closing % tanggal % Shift % belum ada. Revisi hanya untuk Closing yang sudah tersimpan.',
        v_storage, v_row.tanggal, v_row.shift;
    end if;

    if v_existing.actual_qty is not distinct from v_row.actual_qty
       and v_existing.note is not distinct from v_note
       and v_existing.sonding_height_cm is not distinct from v_row.sonding_height_cm
       and v_existing.tera_version is not distinct from v_tera_version then
      continue;
    end if;

    if v_row.shift = 1 then
      v_next_tanggal := v_row.tanggal;
      v_next_shift := 2;
    else
      v_next_tanggal := v_row.tanggal + 1;
      v_next_shift := 1;
    end if;

    v_opening_updated := false;
    select * into v_opening
      from public.stock_opening o
     where o.tanggal = v_next_tanggal
       and o.shift = v_next_shift
       and o.storage = v_storage
     for update;

    if found then
      -- Only touch a carry-forward Opening that still represents the old Closing.
      -- If somebody has independently changed the next Opening, abort the whole revision.
      if v_opening.qty is distinct from v_existing.actual_qty
         or v_opening.sonding_height_cm is distinct from v_existing.sonding_height_cm
         or v_opening.tera_version is distinct from v_existing.tera_version then
        raise exception 'Opening % tanggal % Shift % sudah berbeda dari Closing lama. Revisi dibatalkan agar data shift berikutnya tidak tertimpa.',
          v_storage, v_next_tanggal, v_next_shift;
      end if;

      update public.stock_opening
         set qty = v_row.actual_qty,
             sonding_height_cm = v_row.sonding_height_cm,
             tera_version = v_tera_version
       where id = v_opening.id;

      v_opening_updated := true;
      v_opening_count := v_opening_count + 1;
    end if;

    update public.stock_closing
       set actual_qty = v_row.actual_qty,
           difference_qty = v_row.actual_qty - v_existing.system_qty,
           note = v_note,
           sonding_height_cm = v_row.sonding_height_cm,
           tera_version = v_tera_version
     where id = v_existing.id
     returning * into v_new;

    insert into private.stock_closing_revisions(
      closing_id, tanggal, shift, storage,
      changed_by, changed_by_name, changed_by_role, reason,
      old_data, new_data, opening_updated
    ) values (
      v_existing.id, v_existing.tanggal, v_existing.shift, v_existing.storage,
      auth.uid(), v_actor_name, v_role, v_reason,
      to_jsonb(v_existing), to_jsonb(v_new), v_opening_updated
    );

    v_changed_count := v_changed_count + 1;
  end loop;

  if v_changed_count = 0 then
    raise exception 'Tidak ada perubahan Stock Akhir yang perlu disimpan.';
  end if;

  return jsonb_build_object(
    'ok', true,
    'changed_rows', v_changed_count,
    'opening_rows_updated', v_opening_count,
    'reason', v_reason
  );
end;
$$;

revoke all on function public.revise_stock_closing(jsonb,text) from public, anon;
grant execute on function public.revise_stock_closing(jsonb,text) to authenticated;

comment on function public.revise_stock_closing(jsonb,text) is
  'Revises an existing final Stock Closing. Only GL/Admin may execute successfully; old/new data and reason are journaled. Existing carry-forward Opening is updated only when it still matches the old Closing.';
