create table if not exists public.lubricant_unit_usages (
  id bigint generated by default as identity primary key,
  movement_id bigint not null unique references public.lubricant_movements(id) on delete restrict,
  created_at timestamptz not null default now(),
  tanggal date not null default (timezone('Asia/Jakarta',now()))::date,
  source_storage_id bigint not null references public.lubricant_storages(id),
  product_id bigint not null references public.lubricant_products(id),
  unit_code text not null,
  quantity numeric(14,2) not null check (quantity > 0),
  base_unit text not null check (base_unit in ('L','KG')),
  planner_source text not null default 'MANUAL' check (planner_source in ('WELL','TRACK','MANUAL')),
  planner_ref text,
  mechanic_name text not null,
  mechanic_nrp text,
  hm numeric(14,2),
  shift smallint check (shift in (1,2)),
  note text,
  created_by uuid,
  created_by_name text,
  created_by_role text,
  constraint lubricant_usage_hm_nonnegative check (hm is null or hm >= 0)
);

create index if not exists idx_lubricant_usage_created on public.lubricant_unit_usages(created_at desc);
create index if not exists idx_lubricant_usage_unit on public.lubricant_unit_usages(unit_code, created_at desc);
create index if not exists idx_lubricant_usage_storage_product on public.lubricant_unit_usages(source_storage_id, product_id, created_at desc);

alter table public.lubricant_unit_usages enable row level security;
drop policy if exists lubricant_usage_staff_read on public.lubricant_unit_usages;
create policy lubricant_usage_staff_read on public.lubricant_unit_usages
for select to authenticated
using (coalesce(public.current_staff_role(),'') in ('gl','admin','atasan'));

grant select on public.lubricant_unit_usages to authenticated;

create or replace function public.lubricant_unit_directory()
returns table(code_unit text, egi text, code_ellips text)
language plpgsql
stable
security definer
set search_path=''
as $$
declare v_role text:=coalesce(public.current_staff_role(),'');
begin
  if auth.uid() is null or v_role not in ('gl','admin','atasan') then
    raise exception 'Akun tidak diizinkan membaca master unit.' using errcode='42501';
  end if;
  return query
    select u.code_unit,u.egi,u.code_ellips
    from public.unit_master u
    where coalesce(u.active,true)=true
      and nullif(trim(u.code_unit),'') is not null
    order by u.code_unit;
end;$$;

grant execute on function public.lubricant_unit_directory() to authenticated;

create or replace function public.lubricant_issue_to_unit(
  p_request_id uuid,
  p_source_code text,
  p_product_code text,
  p_unit_code text,
  p_quantity numeric,
  p_planner_source text,
  p_planner_ref text,
  p_mechanic_name text,
  p_mechanic_nrp text,
  p_hm numeric,
  p_shift smallint,
  p_note text
) returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_role text:=coalesce(public.current_staff_role(),'');
  v_source public.lubricant_storages%rowtype;
  v_product public.lubricant_products%rowtype;
  v_existing public.lubricant_movements%rowtype;
  v_move public.lubricant_movements%rowtype;
  v_usage public.lubricant_unit_usages%rowtype;
  v_qty numeric:=round(coalesce(p_quantity,0),2);
  v_before numeric;
  v_after numeric;
  v_name text;
  v_unit text:=upper(trim(coalesce(p_unit_code,'')));
  v_plan text:=upper(trim(coalesce(p_planner_source,'MANUAL')));
  v_mechanic text:=trim(coalesce(p_mechanic_name,''));
begin
  if auth.uid() is null or v_role not in ('gl','admin','atasan') then
    raise exception 'Akun tidak diizinkan mencatat pemakaian lubricant.' using errcode='42501';
  end if;
  if p_request_id is null then raise exception 'Request ID wajib.'; end if;

  select * into v_existing from public.lubricant_movements where request_id=p_request_id;
  if found then
    select * into v_usage from public.lubricant_unit_usages where movement_id=v_existing.id limit 1;
    return jsonb_build_object('ok',true,'replayed',true,'movement',to_jsonb(v_existing),'usage',to_jsonb(v_usage));
  end if;

  if v_qty<=0 then raise exception 'Qty pemakaian wajib lebih dari 0.'; end if;
  if v_unit='' then raise exception 'Unit wajib dipilih.'; end if;
  if v_mechanic='' then raise exception 'Nama mekanik wajib diisi.'; end if;
  if v_plan not in ('WELL','TRACK','MANUAL') then raise exception 'Sumber planner harus WELL, TRACK, atau MANUAL.'; end if;
  if p_shift is not null and p_shift not in (1,2) then raise exception 'Shift harus 1 atau 2.'; end if;
  if p_hm is not null and p_hm<0 then raise exception 'HM tidak valid.'; end if;

  if not exists(select 1 from public.unit_master u where upper(trim(u.code_unit))=v_unit and coalesce(u.active,true)=true) then
    raise exception 'Unit % tidak ditemukan / tidak aktif.',v_unit;
  end if;

  select * into v_product
  from public.lubricant_products
  where upper(code)=upper(trim(p_product_code)) and active=true
  limit 1;
  if not found then raise exception 'Produk lubricant tidak ditemukan.'; end if;

  select * into v_source
  from public.lubricant_storages
  where upper(code)=upper(trim(p_source_code)) and active=true
  limit 1;
  if not found then raise exception 'Storage sumber tidak ditemukan.'; end if;

  if v_product.category='OIL' then
    if v_source.storage_type not in ('LO','LUBE_SKID') then
      raise exception 'Pemakaian oli ke unit harus berasal dari LO atau Lube Skid.';
    end if;
    if not exists(select 1 from public.lubricant_storage_compartments c where c.storage_id=v_source.id and c.product_id=v_product.id and c.active=true) then
      raise exception 'Produk ini tidak tersedia pada compartment storage sumber.';
    end if;
  elsif v_product.category='GREASE' then
    if v_source.storage_type<>'YARD' then
      raise exception 'Grease ke unit harus berasal dari YARD.';
    end if;
  end if;

  insert into public.lubricant_stock_balances(storage_id,product_id,quantity)
  values(v_source.id,v_product.id,0)
  on conflict(storage_id,product_id) do nothing;

  perform pg_advisory_xact_lock(hashtextextended('lubricant:'||v_source.id||':'||v_product.id,0));
  select quantity into v_before
  from public.lubricant_stock_balances
  where storage_id=v_source.id and product_id=v_product.id
  for update;

  if coalesce(v_before,0)<v_qty then
    raise exception 'Stock % tidak cukup. Tersedia % %, diminta % %.',v_source.code,coalesce(v_before,0),v_product.base_unit,v_qty,v_product.base_unit;
  end if;

  v_after:=v_before-v_qty;
  update public.lubricant_stock_balances
  set quantity=v_after,updated_at=now()
  where storage_id=v_source.id and product_id=v_product.id;

  select display_name into v_name
  from public.staff_profiles
  where user_id=auth.uid() and active=true
  limit 1;

  insert into public.lubricant_movements(
    request_id,movement_type,product_id,source_storage_id,quantity,base_unit,document_no,note,
    source_balance_before,source_balance_after,created_by,created_by_name,created_by_role
  ) values(
    p_request_id,'USAGE',v_product.id,v_source.id,v_qty,v_product.base_unit,
    nullif(trim(coalesce(p_planner_ref,'')),''),nullif(trim(coalesce(p_note,'')),''),
    v_before,v_after,auth.uid(),v_name,v_role
  ) returning * into v_move;

  insert into public.lubricant_unit_usages(
    movement_id,source_storage_id,product_id,unit_code,quantity,base_unit,planner_source,planner_ref,
    mechanic_name,mechanic_nrp,hm,shift,note,created_by,created_by_name,created_by_role
  ) values(
    v_move.id,v_source.id,v_product.id,v_unit,v_qty,v_product.base_unit,v_plan,
    nullif(trim(coalesce(p_planner_ref,'')),''),v_mechanic,nullif(trim(coalesce(p_mechanic_nrp,'')),''),
    p_hm,p_shift,nullif(trim(coalesce(p_note,'')),''),auth.uid(),v_name,v_role
  ) returning * into v_usage;

  return jsonb_build_object('ok',true,'replayed',false,'movement',to_jsonb(v_move),'usage',to_jsonb(v_usage));
end;$$;

grant execute on function public.lubricant_issue_to_unit(uuid,text,text,text,numeric,text,text,text,text,numeric,smallint,text) to authenticated;

comment on table public.lubricant_unit_usages is 'Oil/grease logsheet pemakaian ke unit. Movement USAGE tetap menjadi ledger stock, detail unit/mekanik/planner disimpan di sini.';
