-- KPP-FMS: Master MT / FT
-- Central registry for storage assets. Existing operational storages are seeded.

create table if not exists public.storage_master (
    id bigint generated by default as identity primary key,
    code text not null unique,
    storage_type text not null check (storage_type in ('MT','FT')),
    display_name text,
    warehouse text,
    nominal_capacity_liter numeric(14,1) not null check (nominal_capacity_liter > 0),
    tera_profile text check (tera_profile is null or tera_profile in ('MT','FT')),
    active boolean not null default true,
    sort_order integer not null default 100,
    notes text,
    created_by uuid default auth.uid(),
    updated_by uuid default auth.uid(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint storage_master_code_format check (
        code = upper(code)
        and length(code) between 3 and 20
        and code ~ '^[A-Z0-9_-]+$'
    )
);

comment on table public.storage_master is
'Central master of KPP-FMS mine tanks (MT) and fuel trucks/storage (FT).';
comment on column public.storage_master.tera_profile is
'Existing calibration profile name. NULL means the storage does not yet have a validated tera mapping.';

create index if not exists storage_master_active_sort_idx
    on public.storage_master (active, sort_order, code);
create index if not exists storage_master_type_idx
    on public.storage_master (storage_type, active);

create or replace function public.set_storage_master_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at := now();
    new.updated_by := auth.uid();
    return new;
end;
$$;

drop trigger if exists trg_storage_master_updated_at on public.storage_master;
create trigger trg_storage_master_updated_at
before update on public.storage_master
for each row execute function public.set_storage_master_updated_at();

alter table public.storage_master enable row level security;

drop policy if exists storage_master_read_staff on public.storage_master;
create policy storage_master_read_staff
on public.storage_master
for select
to authenticated
using (
    exists (
        select 1
        from public.staff_profiles p
        where p.user_id = auth.uid()
          and p.active = true
    )
);

drop policy if exists storage_master_insert_lead on public.storage_master;
create policy storage_master_insert_lead
on public.storage_master
for insert
to authenticated
with check (
    exists (
        select 1
        from public.staff_profiles p
        where p.user_id = auth.uid()
          and p.active = true
          and p.role in ('gl','admin','atasan')
    )
);

drop policy if exists storage_master_update_lead on public.storage_master;
create policy storage_master_update_lead
on public.storage_master
for update
to authenticated
using (
    exists (
        select 1
        from public.staff_profiles p
        where p.user_id = auth.uid()
          and p.active = true
          and p.role in ('gl','admin','atasan')
    )
)
with check (
    exists (
        select 1
        from public.staff_profiles p
        where p.user_id = auth.uid()
          and p.active = true
          and p.role in ('gl','admin','atasan')
    )
);

revoke all on public.storage_master from anon;
grant select, insert, update on public.storage_master to authenticated;
grant usage, select on sequence public.storage_master_id_seq to authenticated;

insert into public.storage_master
    (code, storage_type, display_name, warehouse, nominal_capacity_liter, tera_profile, active, sort_order, notes)
values
    ('MT01','MT','MT01',null,40000,'MT',true,10,'Storage existing KPP-FMS'),
    ('MT02','MT','MT02',null,40000,'MT',true,20,'Storage existing KPP-FMS'),
    ('MT03','MT','MT03',null,40000,'MT',true,30,'Storage existing KPP-FMS'),
    ('MT04','MT','MT04',null,40000,'MT',true,40,'Storage existing KPP-FMS'),
    ('FT0073','FT','FT0073','WH FT02',20000,'FT',true,50,'Storage existing KPP-FMS'),
    ('FT0075','FT','FT0075','WH FT01',20000,'FT',true,60,'Storage existing KPP-FMS')
on conflict (code) do nothing;
