create table if not exists public.lubricant_planner_jobs (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('WELL','TRACK')),
  external_ref text not null,
  planned_date date,
  shift smallint check (shift in (1,2)),
  unit_code text not null,
  work_description text,
  mechanic_name text,
  mechanic_nrp text,
  status text not null default 'OPEN' check (status in ('OPEN','USED','CANCELLED')),
  used_movement_id bigint unique references public.lubricant_movements(id) on delete restrict,
  used_at timestamptz,
  import_batch uuid,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source,external_ref)
);

alter table public.lubricant_unit_usages
  add column if not exists planner_job_id bigint references public.lubricant_planner_jobs(id) on delete restrict;

create index if not exists idx_lubricant_planner_open on public.lubricant_planner_jobs(status,planned_date,source);
create index if not exists idx_lubricant_planner_unit on public.lubricant_planner_jobs(unit_code,status,planned_date);
create index if not exists idx_lubricant_usage_planner_job on public.lubricant_unit_usages(planner_job_id) where planner_job_id is not null;

alter table public.lubricant_planner_jobs enable row level security;
drop policy if exists lubricant_planner_staff_read on public.lubricant_planner_jobs;
create policy lubricant_planner_staff_read on public.lubricant_planner_jobs
for select to authenticated
using (coalesce(public.current_staff_role(),'') in ('gl','admin','atasan'));

grant select on public.lubricant_planner_jobs to authenticated;

create or replace function public.lubricant_planner_upsert_jobs(
  p_source text,
  p_rows jsonb
) returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_role text:=coalesce(public.current_staff_role(),'');
  v_source text:=upper(trim(coalesce(p_source,'')));
  v_row jsonb;
  v_ref text;
  v_unit text;
  v_desc text;
  v_date date;
  v_shift smallint;
  v_mechanic text;
  v_nrp text;
  v_batch uuid:=gen_random_uuid();
  v_existing_status text;
  v_imported integer:=0;
  v_skipped_used integer:=0;
  v_total integer:=0;
begin
  if auth.uid() is null or v_role not in ('gl','admin','atasan') then
    raise exception 'Akun tidak diizinkan import planner lubricant.' using errcode='42501';
  end if;
  if v_source not in ('WELL','TRACK') then raise exception 'Sumber planner harus WELL atau TRACK.'; end if;
  if p_rows is null or jsonb_typeof(p_rows)<>'array' or jsonb_array_length(p_rows)=0 then
    raise exception 'Data planner kosong.';
  end if;
  if jsonb_array_length(p_rows)>500 then raise exception 'Maksimal 500 baris per import.'; end if;

  for v_row in select value from jsonb_array_elements(p_rows)
  loop
    v_total:=v_total+1;
    v_ref:=trim(coalesce(v_row->>'external_ref',''));
    v_unit:=upper(trim(coalesce(v_row->>'unit_code','')));
    v_desc:=nullif(trim(coalesce(v_row->>'work_description','')),'');
    v_mechanic:=nullif(trim(coalesce(v_row->>'mechanic_name','')),'');
    v_nrp:=nullif(trim(coalesce(v_row->>'mechanic_nrp','')),'');
    v_date:=null;
    v_shift:=null;

    if nullif(trim(coalesce(v_row->>'planned_date','')),'') is not null then
      begin v_date:=(v_row->>'planned_date')::date; exception when others then raise exception 'Baris %: tanggal tidak valid (%).',v_total,v_row->>'planned_date'; end;
    end if;
    if nullif(trim(coalesce(v_row->>'shift','')),'') is not null then
      begin v_shift:=(v_row->>'shift')::smallint; exception when others then raise exception 'Baris %: shift tidak valid.',v_total; end;
      if v_shift not in (1,2) then raise exception 'Baris %: shift harus 1 atau 2.',v_total; end if;
    end if;

    if v_ref='' then raise exception 'Baris %: WO / Task / Ref wajib.',v_total; end if;
    if v_unit='' then raise exception 'Baris %: unit wajib.',v_total; end if;
    if not exists(select 1 from public.unit_master u where upper(trim(u.code_unit))=v_unit and coalesce(u.active,true)=true) then
      raise exception 'Baris %: unit % tidak ditemukan / tidak aktif di Master Unit.',v_total,v_unit;
    end if;

    select status into v_existing_status
    from public.lubricant_planner_jobs
    where source=v_source and external_ref=v_ref;

    if v_existing_status='USED' then
      v_skipped_used:=v_skipped_used+1;
    else
      insert into public.lubricant_planner_jobs(
        source,external_ref,planned_date,shift,unit_code,work_description,mechanic_name,mechanic_nrp,
        status,import_batch,raw_payload,updated_at
      ) values(
        v_source,v_ref,v_date,v_shift,v_unit,v_desc,v_mechanic,v_nrp,
        'OPEN',v_batch,v_row,now()
      )
      on conflict(source,external_ref) do update set
        planned_date=excluded.planned_date,
        shift=excluded.shift,
        unit_code=excluded.unit_code,
        work_description=excluded.work_description,
        mechanic_name=excluded.mechanic_name,
        mechanic_nrp=excluded.mechanic_nrp,
        status='OPEN',
        import_batch=excluded.import_batch,
        raw_payload=excluded.raw_payload,
        updated_at=now();
      v_imported:=v_imported+1;
    end if;
  end loop;

  return jsonb_build_object('ok',true,'source',v_source,'batch_id',v_batch,'total',v_total,'imported',v_imported,'skipped_used',v_skipped_used);
end;$$;

create or replace function public.lubricant_planner_set_status(
  p_job_id bigint,
  p_status text
) returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_role text:=coalesce(public.current_staff_role(),'');
  v_status text:=upper(trim(coalesce(p_status,'')));
  v_job public.lubricant_planner_jobs%rowtype;
begin
  if auth.uid() is null or v_role not in ('gl','admin','atasan') then
    raise exception 'Akun tidak diizinkan mengubah planner lubricant.' using errcode='42501';
  end if;
  if v_status not in ('OPEN','CANCELLED') then raise exception 'Status hanya OPEN atau CANCELLED.'; end if;
  select * into v_job from public.lubricant_planner_jobs where id=p_job_id for update;
  if not found then raise exception 'Planner job tidak ditemukan.'; end if;
  if v_job.status='USED' then raise exception 'Planner job sudah dipakai dan tidak boleh diubah.'; end if;
  update public.lubricant_planner_jobs set status=v_status,updated_at=now() where id=p_job_id returning * into v_job;
  return jsonb_build_object('ok',true,'job',to_jsonb(v_job));
end;$$;

create or replace function public.lubricant_issue_to_unit_v2(
  p_request_id uuid,
  p_source_code text,
  p_product_code text,
  p_unit_code text,
  p_quantity numeric,
  p_planner_source text,
  p_planner_ref text,
  p_mechanic_name text,
  p_mechanic_nrp text,
  p_hm numeric,
  p_shift smallint,
  p_note text,
  p_planner_job_id bigint
) returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_role text:=coalesce(public.current_staff_role(),'');
  v_job public.lubricant_planner_jobs%rowtype;
  v_existing public.lubricant_movements%rowtype;
  v_existing_usage public.lubricant_unit_usages%rowtype;
  v_result jsonb;
  v_move_id bigint;
  v_plan text:=upper(trim(coalesce(p_planner_source,'MANUAL'));
  v_ref text:=nullif(trim(coalesce(p_planner_ref,'')),'');
  v_mechanic text:=nullif(trim(coalesce(p_mechanic_name,'')),'');
  v_nrp text:=nullif(trim(coalesce(p_mechanic_nrp,'')),'');
  v_shift smallint:=p_shift;
begin
  if auth.uid() is null or v_role not in ('gl','admin','atasan') then
    raise exception 'Akun tidak diizinkan mencatat pemakaian lubricant.' using errcode='42501';
  end if;

  select * into v_existing from public.lubricant_movements where request_id=p_request_id;
  if found then
    select * into v_existing_usage from public.lubricant_unit_usages where movement_id=v_existing.id limit 1;
    return jsonb_build_object('ok',true,'replayed',true,'movement',to_jsonb(v_existing),'usage',to_jsonb(v_existing_usage));
  end if;

  if p_planner_job_id is not null then
    select * into v_job from public.lubricant_planner_jobs where id=p_planner_job_id for update;
    if not found then raise exception 'Planner job tidak ditemukan.'; end if;
    if v_job.status<>'OPEN' then raise exception 'Planner job % sudah berstatus %.',v_job.external_ref,v_job.status; end if;
    if upper(trim(coalesce(p_unit_code,'')))<>upper(trim(v_job.unit_code)) then
      raise exception 'Unit pemakaian harus sama dengan planner job (%).',v_job.unit_code;
    end if;
    v_plan:=v_job.source;
    v_ref:=v_job.external_ref;
    v_mechanic:=coalesce(v_mechanic,v_job.mechanic_name);
    v_nrp:=coalesce(v_nrp,v_job.mechanic_nrp);
    v_shift:=coalesce(v_shift,v_job.shift);
  end if;

  v_result:=public.lubricant_issue_to_unit(
    p_request_id,p_source_code,p_product_code,p_unit_code,p_quantity,
    v_plan,v_ref,v_mechanic,v_nrp,p_hm,v_shift,p_note
  );

  v_move_id:=nullif(v_result->'movement'->>'id','')::bigint;
  if p_planner_job_id is not null and v_move_id is not null then
    update public.lubricant_planner_jobs
      set status='USED',used_movement_id=v_move_id,used_at=now(),updated_at=now()
    where id=p_planner_job_id;
    update public.lubricant_unit_usages
      set planner_job_id=p_planner_job_id
    where movement_id=v_move_id;
  end if;

  return v_result || jsonb_build_object('planner_job_id',p_planner_job_id);
end;$$;

revoke all on function public.lubricant_planner_upsert_jobs(text,jsonb) from public,anon;
revoke all on function public.lubricant_planner_set_status(bigint,text) from public,anon;
revoke all on function public.lubricant_issue_to_unit_v2(uuid,text,text,text,numeric,text,text,text,text,numeric,smallint,text,bigint) from public,anon;

grant execute on function public.lubricant_planner_upsert_jobs(text,jsonb) to authenticated;
grant execute on function public.lubricant_planner_set_status(bigint,text) to authenticated;
grant execute on function public.lubricant_issue_to_unit_v2(uuid,text,text,text,numeric,text,text,text,text,numeric,smallint,text,bigint) to authenticated;

comment on table public.lubricant_planner_jobs is 'Inbox pekerjaan lubricant dari export WELL/TRACK. Job OPEN dapat dipilih di Oil Logsheet; saat usage tersimpan, job menjadi USED secara atomik.';
